### ISSUE TITLE
got error on running command react-native run-android

### ISSUE THREAD

**Issue by usamaehsan** [lhlhlh111000/rn-multi-bundle#4]
Starting: Intent { cmp=com.metrotest/.MainActivity }
Error type 3
Error: Activity class {com.metrotest/com.metrotest.MainActivity} does not exist.

**Comment by lhlhlh111000** [comment]
@usamaehsan Because i had modify the main entry of this project；you can try this command "react-native run-android --main-activity act.MainActivity".  and it will fine.

**Comment by usamaehsan** [comment]
Thanks for reply,I really appreciate it.

**Comment by usamaehsan** [comment]
@lhlhlh111000 i have one more question
can we load bundles by using loadScriptFromAssets in some native module from react native button click?
if yes can you please explain me how?
i have tried it but it does not open anything if bundle is not available it gives error but if its available in assets it does not do anything on click of button.

**Comment by usamaehsan** [comment]
i am trying to create plugins app where user can install plugin bundle from react native side and there could be 1000 of plugins
